version: '3'

services:
  app:
    build: 
      context: ./
    container_name: app
    entrypoint: docker-entrypoint.sh 
    command: bash -c "npm install && node index.js"
    volumes: 
      - .:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
